FROM python:3.11-slim

WORKDIR /app

COPY fastapi-requirements.txt .
RUN pip install -r fastapi-requirements.txt

COPY src ./src
COPY models ./models

ENV PYTHONPATH=/app

CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]